### Overview of the Iris Classification Project

The Iris classification project involves building a neural network model to classify different species of Iris flowers based on their physical features. The Iris dataset is a well-known dataset in machine learning that consists of 150 instances, with four features: sepal length, sepal width, petal length, and petal width. The goal is to predict the species of the flower from three possible classes: Iris Setosa, Iris Versicolor, and Iris Virginica.

Key Steps in the Project:


    Data Loading and Preprocessing:


        The dataset was loaded from a UCI Machine Learning repository.

        Features were standardized using StandardScaler for better model performance.

        The species labels were one-hot encoded to facilitate multi-class classification.

        The dataset was split into training and testing sets to evaluate the model's performance.



    Model Building:


        A Sequential neural network model was created using Keras.

        The model consisted of an input layer, two hidden layers with ReLU activation functions, and an output layer with softmax activation to handle multi-class classification.

        The model was compiled using the Adam optimizer and categorical cross-entropy loss function.



    Model Training:


        The model was trained on the training set with a specified number of epochs and batch size.

        A validation split was used to monitor model performance during training.



    Model Evaluation:


        The trained model was evaluated on the test set.

        Performance metrics, including confusion matrix and classification report, were generated to assess accuracy and other classification metrics.





In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [2]:
# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
data = pd.read_csv(url, header=None, names=columns)

In [4]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
# Encode categorical labels
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [8]:
encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y.reshape(-1, 1))

In [9]:
# Normalize feature data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [10]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
# Build the model
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu'))  # 4 input features
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))  # 3 classes for Iris species

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

C:\Users\MAC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
model.fit(X_train, y_train, epochs=100, batch_size=5, validation_split=0.2)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 5s 77ms/step - accuracy: 0.2383 - loss: 1.1485 - val_accuracy: 0.5417 - val_loss: 0.8210
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.3458 - loss: 0.9787 - val_accuracy: 0.6250 - val_loss: 0.7638
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5644 - loss: 0.9230 - val_accuracy: 0.7083 - val_loss: 0.7179
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6745 - loss: 0.8711 - val_accuracy: 0.7500 - val_loss: 0.6743
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.6900 - loss: 0.7840 - val_accuracy: 0.7500 - val_loss: 0.6348
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.6897 - loss: 0.7687 - val_accuracy: 0.8333 - val_loss: 0.5943
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7309 - loss: 0.6686 - val_accuracy: 0.8750 - val_loss: 0.5548
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8102 - loss: 0.5995 - val_accuracy: 0.

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)
y_true_classes = y_test.argmax(axis=1)

print(confusion_matrix(y_true_classes, y_pred_classes))
print(classification_report(y_true_classes, y_pred_classes))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [32]:
from keras.datasets import mnist
from keras.utils import to_categorical

# Load dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Reshape and normalize
X_train = X_train.reshape((X_train.shape[0], 28 * 28)).astype('float32') / 255
X_test = X_test.reshape((X_test.shape[0], 28 * 28)).astype('float32') / 255

# One-hot encode labels
y_train_encoded = to_categorical(y_train, num_classes=10)
y_test_encoded = to_categorical(y_test, num_classes=10)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


In [34]:
# Build the model
model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))  # 784 input features
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))  # 10 classes for digits 0-9

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


C:\Users\MAC\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [36]:
model.fit(X_train, y_train_encoded, epochs=10, batch_size=32, validation_split=0.2)


Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.8672 - loss: 0.4614 - val_accuracy: 0.9613 - val_loss: 0.1298
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9632 - loss: 0.1216 - val_accuracy: 0.9653 - val_loss: 0.1189
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9752 - loss: 0.0783 - val_accuracy: 0.9708 - val_loss: 0.0994
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9816 - loss: 0.0587 - val_accuracy: 0.9672 - val_loss: 0.1121
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9856 - loss: 0.0445 - val_accuracy: 0.9755 - val_loss: 0.0912
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 15s 10ms/step - accuracy: 0.9900 - loss: 0.0313 - val_accuracy: 0.9748 - val_loss: 0.0887
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9897 - loss: 0.0313 - val_accuracy: 0.9741 - val_loss: 0.1055
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9930 - loss: 

In [40]:
# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)

print(confusion_matrix(y_test, y_pred_classes))
print(classification_report(y_test, y_pred_classes))

313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step
[[ 971    0    0    2    0    2    1    2    2    0]
 [   0 1122    0    2    0    2    2    1    6    0]
 [   6    3  987    9    4    0    1    6   14    2]
 [   2    0    0  987    0    8    0    5    7    1]
 [   1    1    1    0  960    1    3    2    1   12]
 [   2    0    0    4    1  874    6    0    3    2]
 [   2    3    1    1    5    5  937    1    3    0]
 [   0    7    7    2    0    1    0 1000    2    9]
 [   2    0    1    4    0    6    0    3  956    2]
 [   2    3    0    4   11    4    0    7    4  974]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.99      0.96      0.97      1032
           3       0.97      0.98      0.97      1010
           4       0.98      0.98      0.98       982
           5       0.97      0.98      0.97       892
           6       0.99      0.98      0.98     

### Conclusion

The Iris classification project successfully demonstrated the application of neural networks for multi-class classification tasks. The model achieved a high level of accuracy in predicting the species of Iris flowers based on their physical attributes. 

Key Takeaways:


    Effectiveness of Neural Networks: The project showcased how neural networks can effectively learn from data and make accurate predictions.

    Importance of Data Preprocessing: Standardizing features and encoding labels are crucial steps that can significantly impact the performance of machine learning models.

    Model Evaluation: Utilizing confusion matrices and classification reports provides valuable insights into model performance beyond just accuracy, allowing for a deeper understanding of how well the model performs across different classes.


Overall, this project serves as a foundational example for applying machine learning techniques to real-world problems, paving the way for more complex applications in areas like image classification, natural language processing, and beyond.