## Create a numpy array called "grades" that contains the following grades: [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]


 ### Instructions

##### Create a new file called "grades_analysis.py"
##### Import the numpy library and create the "grades" array as specified above.
##### Use numpy functions to calculate the mean, median, and standard deviation of the grades.
##### Use numpy function to find the maximum and minimum of the grades.
##### Use numpy function to sort the grades in ascending order.
##### Use numpy function to find the index of the highest grade in the array.
##### Use numpy function to count the number of students who scored above 90.
##### Use numpy function to calculate the percentage of students who scored above 90.
##### Use numpy function to calculate the percentage of students who scored below 75.
##### Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
##### Create a new array called "passing_grades" that contains all the grades above 75.
##### Print the result of all the above steps.
## Note:

##### to calculate percentage use numpy.mean(grades > 90) * 100
##### to extract the grades above 90 use grades[grades > 90]
##### to extract the grades above 75 use grades[grades > 75]
##### You can use other numpy functions as well to analyze the data as you want. The above steps are just examples of what can be done

In [2]:
import numpy as np

In [18]:
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98]) #assign the array to a name "grades"

In [22]:
grades

array([85, 90, 88, 92, 95, 80, 75, 98])

In [24]:
np.mean(grades) #print the mean

87.875

In [26]:
np.median(grades) #print the median

89.0

In [28]:
np.std(grades) #print the standard deviation

7.166545541612082

In [30]:
np.max(grades) #print the maximum number in the array

98

In [32]:
np.min(grades) #print the minimum number in the array

75

In [34]:
#Use numpy function to sort the grades in ascending order.
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98])
sorted_grades= np.sort(grades)
sorted_grades

array([75, 80, 85, 88, 90, 92, 95, 98])

In [50]:
#Use numpy function to find the index of the highest grade in the array.
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98])
highest_grade = np.max(grades)
highest_grade_index = np.where(grades ==highest_grade)[0][0]
highest_grade_index

7

In [44]:
highest_grade_index = np.argmax(grades)
highest_grade_index

7

In [54]:
#Use numpy function to count the number of students who scored above 90.
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98])
studentscore_above_90 = np.sum(grades>90)
studentscore_above_90

3

In [60]:
#Use numpy function to calculate the percentage of students who scored above 90.
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98])
percentage_score_above_90 = np.mean(grades > 90) * 100
percentage_score_above_90

37.5

In [64]:
#Use numpy function to calculate the percentage of students who scored below 75
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98])
percentage_score_below_75 = np.mean(grades < 75) * 100
percentage_score_below_75

0.0

In [70]:
#Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
grades =np.array([85, 90, 88, 92, 95, 80, 75, 98])
high_performers= grades[grades > 90]
high_performers

array([92, 95, 98])

In [74]:
#Create a new array called "passing_grades" that contains all the grades above 75.
passing_grades = grades[grades >75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98])